apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: dynatrace-database-datasource
    app.kubernetes.io/name: dynatrace-operator
    app.kubernetes.io/version: v0.1.35
  name: dynatrace-database-extensions-executor
