apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: dynatrace-database-datasource
    app.kubernetes.io/name: dynatrace-operator
    app.kubernetes.io/version: 0.1.63
  name: dynatrace-database-extensions-executor
